micronaut:
  application:
    name: mentoringBackend
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
    versioning:
      enabled: true
      default-version: 1
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
  server:
    port: 8087
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:9000
---
#tag::security[]
micronaut:
  security:
    authentication: bearer # <1>
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <2>
#end::security[]
---
#tag::refresh[]
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <1>
          access-token:
            expiration: 600000
#end::refresh[]
---
# management endpoints settings
endpoints:

  all:
    enabled: false
    sensitive: false
  stop:
    enabled: false
---
netty:
  default:
    allocator:
      max-order: 3
---
# JSON settings
jackson:
  property-naming-strategy: LOWER_CAMEL_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
---
# DB sources
datasources:
  default:
    url: jdbc:mariadb://localhost:3307/mentoring
    username: root
    password: root
    schema-generate: NONE
    db-type: mariadb
    dialect: MYSQL
    driver-class-name: org.mariadb.jdbc.Driver
---
#liquibase
liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:db/liquibase-changelog.xml
      drop-first: false
---
# micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "mz.org.fgh.mentoring.entity"
    properties:
      hibernate:
        show_sql: false