name: Verify Commits and Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  verify-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify commit messages
        run: |
          git log --format=%s -n 1 | grep -Eq '^(feat|fix|chore|docs|style|refactor|perf|test|ci|build|revert): '
        shell: bash
        continue-on-error: false

      - name: Set up Micronaut
        run: sdk install micronaut

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
